# -*- coding: utf-8 -*-
"""PAGOS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dzXKNZjMrOepBlEkhFbYowBJgerKtK7c
"""

class MetodoPago:
    def pagar(self, monto):
        raise NotImplementedError("Este método debe ser implementado por las subclases.")

# 💳 Estrategia: Pago con tarjeta de crédito
class PagoConTarjeta(MetodoPago):
    def pagar(self, monto):
        print(f"💳 Pagando ${monto:.2f} con tarjeta de crédito... ✅ Aprobado.")

# 💻 Estrategia: Pago con PayPal
class PagoConPayPal(MetodoPago):
    def pagar(self, monto):
        print(f"💻 Pagando ${monto:.2f} con PayPal... ✅ Transacción completada.")

# 🪙 Estrategia: Pago con criptomonedas
class PagoConCripto(MetodoPago):
    def pagar(self, monto):
        print(f"🪙 Pagando ${monto:.2f} con criptomonedas... ✅ Confirmado en blockchain.")

# 🧾 Clase principal que usa la estrategia de pago
class ProcesadorPago:
    def __init__(self, metodo_pago: MetodoPago):
        self.metodo_pago = metodo_pago  # Se puede cambiar dinámicamente

    def procesar_pago(self, monto):
        self.metodo_pago.pagar(monto)

# 📋 Menú interactivo para elegir forma de pago
def menu_pagos():
    while True:
        print("\n🔹 MÉTODOS DE PAGO DISPONIBLES:")
        print("1. Tarjeta de crédito")
        print("2. PayPal")
        print("3. Criptomonedas")
        print("4. Salir")

        opcion = input("👉 Elige una opción (1-4): ")

        if opcion == "4":
            print("👋 Saliendo del sistema de pago.")
            break

        monto = input("💰 Ingresa el monto a pagar: $")
        try:
            monto = float(monto)
        except:
            print("❌ Monto inválido. Intenta de nuevo.")
            continue

        # Seleccionar estrategia según la opción
        if opcion == "1":
            metodo = PagoConTarjeta()
        elif opcion == "2":
            metodo = PagoConPayPal()
        elif opcion == "3":
            metodo = PagoConCripto()
        else:
            print("❌ Opción inválida. Intenta de nuevo.")
            continue

        # Usar el procesador con la estrategia seleccionada
        procesador = ProcesadorPago(metodo)
        procesador.procesar_pago(monto)

# ▶️ Ejecutar el menú
menu_pagos()